# Исключения

Исключения выбрасываются с помощью функции `throw`:

```ride
func main(amount: Int) = {
   if (amount > 0)
   then
        "Done!"
   else
        throw("Error!")
}
```

Функция `throw` имеет возвращаемый тип [Nothing](/ru/ride/data-types/).

В Ride нет обработки исключений. После того как исключение было выброшено, скрипт прекратит свое выполнение. Транзакция при этом будет считаться неудавшейся и не будет включена в блок.